# == Font ================================================================={{{

[font]
# family = "Mononoki Nerd Font"
size = 8

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Regular Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

# }}}

# == Window ================================================================{{{

# [window]
# opacity = 1.0 # set to < 1 for transparent background

# }}}

# NOTE:
# If you get an `unused key: ...` error, it means that you should remove it
# because it's not used.
